# Generated by Django 5.2.11 on 2026-06-12 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
    ]
