# Generated by Django 5.2.11 on 2026-06-13 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'permissions': [('print_event', 'Can print events summaries and logs')], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
    ]
