# Generated by Django 5.2.11 on 2026-06-12 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_transaction_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'default_permissions': ('add', 'view'), 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
    ]
