# Generated by Django 5.2.11 on 2026-06-13 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_transaction_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'default_permissions': ('add', 'view'), 'permissions': [('print_transaction', 'Can print financial ledger registry indices')], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
    ]
