# Generated by Django 5.2.11 on 2026-06-12 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'default_permissions': ('add', 'view'), 'verbose_name': 'Inventory Item', 'verbose_name_plural': 'Inventory Items'},
        ),
    ]
