# Generated by Django 5.2.11 on 2026-06-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendancerecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
