# Generated by Django 5.2.11 on 2026-06-12 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_studentprofile_middle_initial_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'default_permissions': ('add', 'view')},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'default_permissions': ('add', 'view')},
        ),
    ]
