# Generated by Django 5.2.11 on 2026-06-13 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendancerecord_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'default_permissions': ('add', 'view'), 'permissions': [('print_attendancerecord', 'Can print historical attendance records')]},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'default_permissions': ('add', 'view'), 'permissions': [('print_studentprofile', 'Can print student profile rosters')]},
        ),
    ]
